export const SEED_APPLICANTS = [
  {
    id: 'applicant-aarav-sharma',
    fullName: 'Aarav Sharma',
    email: 'aarav.sharma@example.com',
    phone: '+91 98234 56789',
    city: 'Pune',
    state: 'Maharashtra',
    country: 'India',
    targetIntake: 'Winter Semester 2025/26',
    availabilityDate: new Date('2025-08-15'),
    goalTrack: 'Study' as const,
    status: 'ROADMAP_READY' as const,
    provenance: 'VERIFIED' as const,
    createdAt: new Date('2025-01-10T09:00:00Z'),
    updatedAt: new Date(),
    educations: [
      {
        id: 'edu-aarav-1',
        applicantId: 'applicant-aarav-sharma',
        institution: 'Savitribai Phule Pune University (SPPU)',
        qualification: 'Bachelor of Engineering (B.E.) in Computer Engineering',
        fieldOfStudy: 'Computer Science & Engineering',
        startYear: 2020,
        graduationYear: 2024,
        gpaOrPercentage: 8.4,
        maxGpaOrScale: 10.0,
        germanGpaEquivalent: 1.8,
        gradingSystem: 'CGPA_10',
        isIndianDegree: true,
        degreeType: 'FOUR_YEAR_BACHELOR' as const,
        anabinStatus: 'H+',
        isVerified: true,
        provenance: 'VERIFIED' as const,
        createdAt: new Date('2025-01-10T09:10:00Z'),
        updatedAt: new Date(),
      },
      {
        id: 'edu-aarav-2',
        applicantId: 'applicant-aarav-sharma',
        institution: 'Delhi Public School (CBSE Board)',
        qualification: 'Higher Secondary Certificate (12th PCM)',
        fieldOfStudy: 'Physics, Chemistry, Mathematics & CS',
        startYear: 2018,
        graduationYear: 2020,
        gpaOrPercentage: 91.4,
        maxGpaOrScale: 100.0,
        germanGpaEquivalent: 1.4,
        gradingSystem: 'PERCENTAGE',
        isIndianDegree: true,
        degreeType: 'TWELFTH_GRADE' as const,
        anabinStatus: 'H+',
        isVerified: true,
        provenance: 'VERIFIED' as const,
        createdAt: new Date('2025-01-10T09:12:00Z'),
        updatedAt: new Date(),
      },
    ],
    employments: [
      {
        id: 'emp-aarav-1',
        applicantId: 'applicant-aarav-sharma',
        employer: 'Infosys Limited',
        role: 'Systems Engineer (Cloud & AI Backend)',
        responsibilities:
          'Engineered microservices using Node.js, NestJS, and AWS DynamoDB; implemented automated Docker CI/CD pipelines.',
        startDate: new Date('2024-06-01'),
        endDate: null,
        isCurrent: true,
        totalMonths: 14,
        industry: 'IT / Software',
        isVerified: true,
        provenance: 'VERIFIED' as const,
        createdAt: new Date('2025-01-10T09:15:00Z'),
        updatedAt: new Date(),
      },
    ],
    languages: [
      {
        id: 'lang-aarav-1',
        applicantId: 'applicant-aarav-sharma',
        language: 'German',
        level: 'A2',
        certificateName: 'Goethe-Zertifikat A2 (Max Mueller Bhavan Pune)',
        score: '84/100 (Gut)',
        isVerified: true,
        provenance: 'VERIFIED' as const,
        createdAt: new Date('2025-01-10T09:20:00Z'),
        updatedAt: new Date(),
      },
      {
        id: 'lang-aarav-2',
        applicantId: 'applicant-aarav-sharma',
        language: 'English',
        level: 'C1',
        certificateName: 'IELTS Academic (IDP India)',
        score: '7.5 (L: 8.5, R: 8.0, W: 7.0, S: 7.0)',
        isVerified: true,
        provenance: 'VERIFIED' as const,
        createdAt: new Date('2025-01-10T09:22:00Z'),
        updatedAt: new Date(),
      },
    ],
    documents: [
      {
        id: 'doc-aarav-1',
        applicantId: 'applicant-aarav-sharma',
        title: 'Pune University B.E. Degree Certificate & Transcript',
        docType: 'DEGREE_CERTIFICATE' as const,
        fileUrl: '/uploads/samples/aarav_sppu_degree.pdf',
        fileName: 'aarav_sppu_degree.pdf',
        fileSizeBytes: 2450000,
        mimeType: 'application/pdf',
        extractionFlags: {
          parsed: true,
          ocrConfidence: 0.98,
          detectedInstitution: 'Savitribai Phule Pune University',
          detectedGrade: '8.4 CGPA',
          anabinRecognized: true,
        },
        extractedData: {
          universityName: 'Savitribai Phule Pune University',
          degreeConferred: 'Bachelor of Engineering',
          department: 'Computer Engineering',
          yearOfPassing: 2024,
          overallGrade: 'First Class with Distinction (8.4 CGPA)',
        },
        verificationState: 'VERIFIED' as const,
        verificationNotes: 'Institutional accreditation H+ verified against German KMK Anabin database.',
        uploadedAt: new Date('2025-01-10T09:25:00Z'),
        updatedAt: new Date(),
      },
      {
        id: 'doc-aarav-2',
        applicantId: 'applicant-aarav-sharma',
        title: 'Goethe-Zertifikat A2 Scorecard',
        docType: 'LANGUAGE_CERTIFICATE' as const,
        fileUrl: '/uploads/samples/aarav_goethe_a2.pdf',
        fileName: 'aarav_goethe_a2.pdf',
        fileSizeBytes: 1120000,
        mimeType: 'application/pdf',
        extractionFlags: {
          parsed: true,
          ocrConfidence: 0.99,
          issuer: 'Goethe-Institut',
          cefrLevel: 'A2',
        },
        extractedData: {
          issuer: 'Goethe-Institut Max Mueller Bhavan',
          level: 'A2',
          reading: 22,
          listening: 21,
          writing: 20,
          speaking: 21,
          totalScore: '84/100',
        },
        verificationState: 'VERIFIED' as const,
        verificationNotes: 'Official Goethe-Zertifikat registration ID valid.',
        uploadedAt: new Date('2025-01-10T09:28:00Z'),
        updatedAt: new Date(),
      },
    ],
    motivationMedia: {
      id: 'mot-aarav-1',
      applicantId: 'applicant-aarav-sharma',
      primaryReasonToMigrate:
        'To pursue world-class Master of Science research in Artificial Intelligence & Distributed Systems at German TU9 universities, leveraging German engineering standards and post-study opportunities.',
      targetRegionsInGermany: [
        'Bavaria (TUM Munich)',
        'North Rhine-Westphalia (RWTH Aachen)',
        'Baden-Württemberg (University of Stuttgart)',
      ],
      longTermCareerGoals:
        'Become a Senior Cloud & AI Solutions Architect at a major German technology or automotive innovator (SAP, Siemens, BMW).',
      preferredLanguageOfStudyWork: 'English',
      introVideoUrl: '/uploads/videos/aarav_intro_pitch.mp4',
      introVideoTranscript:
        'Hallo! I am Aarav Sharma from Pune, India. I hold a 4-year B.E. in Computer Engineering with an 8.4 CGPA and 14 months of cloud backend experience at Infosys. I am passionate about pursuing my M.Sc in Data Science in Germany for Winter 2025. I have already achieved Goethe A2 and IELTS 7.5, and I am actively prepping for Goethe B1. AeroPath AI and Educaro are helping me structure my APS verification and direct university admissions.',
      audioTranscript:
        'Hallo! I am Aarav Sharma from Pune, India. I hold a 4-year B.E. in Computer Engineering with an 8.4 CGPA...',
      sentimentScore: 0.94,
      motivationKeywords: [
        'TU9 Master',
        'Data Science',
        'AI Engineering',
        'Goethe A2 Certified',
        'APS Verification Ready',
      ],
      videoDurationSeconds: 48,
      provenance: 'VERIFIED' as const,
      createdAt: new Date('2025-01-10T09:30:00Z'),
      updatedAt: new Date(),
    },
    recommendation: {
      id: 'rec-aarav-1',
      applicantId: 'applicant-aarav-sharma',
      eligibilityStatus: 'ELIGIBLE' as const,
      completenessScore: 88,
      pathwaySummary:
        'Direct Master Entry (Direkter Hochschulzugang) eligible. 4-year Indian Bachelor from H+ University bypasses Studienkolleg requirement.',
      missingRequirements: [
        {
          id: 'req-1',
          title: 'APS Certificate (Akademische Prüfstelle India)',
          category: 'Legal / Visa',
          severity: 'CRITICAL',
          description:
            'Mandatory academic verification certificate issued by the German Embassy New Delhi. Required for uni-assist and student visa filing.',
          actionType: 'APS_APPLICATION',
          isCompleted: false,
        },
        {
          id: 'req-2',
          title: 'Blocked Account Setup (Sperrkonto €11,908)',
          category: 'Financial Proof',
          severity: 'CRITICAL',
          description:
            'Legal proof of subsistence required by the German Federal Foreign Office (BAföG rate for 2024/2025).',
          actionType: 'BLOCKED_ACCOUNT',
          isCompleted: false,
        },
        {
          id: 'req-3',
          title: 'Advance German to B1 Level',
          category: 'Language Immersion',
          severity: 'RECOMMENDED',
          description:
            'While the Master degree is English-taught, German B1 ensures top Werkstudent (working student) positions at BMW or Siemens.',
          actionType: 'GERMAN_CLASS',
          isCompleted: false,
        },
      ],
      anabinInstitutionalStatus: 'H+ (Full Institutional Recognition)',
      apsRequired: true,
      educaroServiceRouting: [
        {
          packageId: 'EDU-MASTER-EXPRESS',
          serviceName: 'Educaro Master’s Direct Placement & APS Accelerator',
          tier: 'Premium Comprehensive',
          highlight: 'Fast-track APS verification & guaranteed university application handling',
          matchScore: 98,
          features: [
            'End-to-end APS document audit and courier logistics in New Delhi',
            'Selection of up to 6 TU9 & public universities with 0 tuition fees',
            'German academic CV & Statement of Purpose (Motivationsschreiben) crafting',
            'Blocked account setup via German partner bank with insurance bundle',
            'German National Visa (Type D) appointment readiness check',
          ],
        },
        {
          packageId: 'EDU-LANG-B1B2',
          serviceName: 'Educaro German Intensive Language Sprint (A2 -> B2)',
          tier: 'Recommended Addon',
          highlight: 'Goethe/telc exam preparation with native German instructors',
          matchScore: 88,
          features: [
            'Live interactive virtual cohorts matching German working hours',
            'Technical & conversational German vocabulary focus',
            'Official Goethe B1/B2 exam registration support in India',
          ],
        },
      ],
      actionableNextSteps: [
        { step: 1, text: 'Initiate APS India application portal submission with verified transcripts' },
        { step: 2, text: 'Submit English CV & SOP for Educaro faculty review' },
        { step: 3, text: 'Apply to TUM and RWTH Aachen on uni-assist before June 15 deadline' },
        { step: 4, text: 'Open Sperrkonto and book German consulate VFS visa slot' },
      ],
      aiSummaryNotes:
        'Aarav is an ideal candidate for direct German M.Sc. admissions. His SPPU B.E. degree is from an H+ university with German GPA 1.8 (Gut). High probability of admission to top public universities with 0 tuition fees.',
      generatedAt: new Date('2025-01-10T09:35:00Z'),
      updatedAt: new Date(),
    },
  },
  {
    id: 'applicant-ananya-nair',
    fullName: 'Ananya Nair',
    email: 'ananya.nair@example.com',
    phone: '+91 97456 12345',
    city: 'Kochi',
    state: 'Kerala',
    country: 'India',
    targetIntake: 'Autumn 2025',
    availabilityDate: new Date('2025-09-01'),
    goalTrack: 'Ausbildung' as const,
    status: 'ROADMAP_READY' as const,
    provenance: 'VERIFIED' as const,
    createdAt: new Date('2025-01-12T10:00:00Z'),
    updatedAt: new Date(),
    educations: [
      {
        id: 'edu-ananya-1',
        applicantId: 'applicant-ananya-nair',
        institution: 'Kerala University of Health Sciences (KUHS)',
        qualification: 'General Nursing & Midwifery (GNM) Diploma',
        fieldOfStudy: 'Nursing & Patient Care',
        startYear: 2020,
        graduationYear: 2023,
        gpaOrPercentage: 78.5,
        maxGpaOrScale: 100.0,
        germanGpaEquivalent: 2.1,
        gradingSystem: 'PERCENTAGE',
        isIndianDegree: true,
        degreeType: 'DIPLOMA' as const,
        anabinStatus: 'H+',
        isVerified: true,
        provenance: 'VERIFIED' as const,
        createdAt: new Date('2025-01-12T10:05:00Z'),
        updatedAt: new Date(),
      },
    ],
    employments: [
      {
        id: 'emp-ananya-1',
        applicantId: 'applicant-ananya-nair',
        employer: 'Aster Medcity Kochi',
        role: 'Staff Nurse (Intensive Care & Emergency)',
        responsibilities:
          'Patient monitoring, ICU vitals management, medication administration, and physician assistance.',
        startDate: new Date('2023-08-01'),
        endDate: null,
        isCurrent: true,
        totalMonths: 18,
        industry: 'Healthcare / Nursing',
        isVerified: true,
        provenance: 'VERIFIED' as const,
        createdAt: new Date('2025-01-12T10:10:00Z'),
        updatedAt: new Date(),
      },
    ],
    languages: [
      {
        id: 'lang-ananya-1',
        applicantId: 'applicant-ananya-nair',
        language: 'German',
        level: 'B1',
        certificateName: 'telc Deutsch B1 (Goethe/telc Approved Center)',
        score: '265/300 (Gut)',
        isVerified: true,
        provenance: 'VERIFIED' as const,
        createdAt: new Date('2025-01-12T10:15:00Z'),
        updatedAt: new Date(),
      },
      {
        id: 'lang-ananya-2',
        applicantId: 'applicant-ananya-nair',
        language: 'English',
        level: 'B2',
        certificateName: 'OET (Occupational English Test)',
        score: 'Grade B',
        isVerified: true,
        provenance: 'APPLICANT_PROVIDED' as const,
        createdAt: new Date('2025-01-12T10:18:00Z'),
        updatedAt: new Date(),
      },
    ],
    documents: [
      {
        id: 'doc-ananya-1',
        applicantId: 'applicant-ananya-nair',
        title: 'GNM Nursing Diploma & Kerala Nurses and Midwives Council Registration',
        docType: 'DEGREE_CERTIFICATE' as const,
        fileUrl: '/uploads/samples/ananya_nursing_kuhs.pdf',
        fileName: 'ananya_nursing_kuhs.pdf',
        fileSizeBytes: 1890000,
        mimeType: 'application/pdf',
        extractionFlags: {
          parsed: true,
          ocrConfidence: 0.96,
          councilRegistration: 'KNMC-2023-9941',
        },
        extractedData: {
          council: 'Kerala Nurses and Midwives Council',
          registrationStatus: 'Active Registered Nurse & Midwife',
          duration: '3 Years Full Time',
        },
        verificationState: 'VERIFIED' as const,
        verificationNotes: 'KNMC credential valid. Meets prerequisites for German nursing Anerkennung.',
        uploadedAt: new Date('2025-01-12T10:20:00Z'),
        updatedAt: new Date(),
      },
    ],
    motivationMedia: {
      id: 'mot-ananya-1',
      applicantId: 'applicant-ananya-nair',
      primaryReasonToMigrate:
        'To establish a respected nursing career in Germany as a recognized Pflegefachfrau, benefiting from high healthcare standards, paid training stipend (€1,200+/month), and clear permanent residency pathways.',
      targetRegionsInGermany: [
        'North Rhine-Westphalia (Cologne / Düsseldorf)',
        'Hesse (Frankfurt)',
        'Baden-Württemberg',
      ],
      longTermCareerGoals:
        'Complete the German adaptation program (Anpassungslehrgang), obtain full German Nursing license (Approbation/Urkunde), and specialize in Intensive Care (Fachkrankenpflegerin).',
      preferredLanguageOfStudyWork: 'German',
      introVideoUrl: '/uploads/videos/ananya_nurse_pitch.mp4',
      introVideoTranscript:
        'Guten Tag! Mein Name ist Ananya Nair aus Kerala, Indien. Ich bin ausgebildete Krankenschwester mit 18 Monaten Erfahrung auf der Intensivstation. Ich habe telc Deutsch B1 bestanden und bereite mich derzeit auf das B2-Niveau vor. Mein großer Traum ist es, in Deutschland als Pflegefachfrau zu arbeiten. Ich freue mich auf die Unterstützung von Educaro bei der Anerkennung meiner Zeugnisse und der Vermittlung an ein deutsches Krankenhaus.',
      audioTranscript:
        'Guten Tag! Mein Name ist Ananya Nair aus Kerala, Indien. Ich bin ausgebildete Krankenschwester...',
      sentimentScore: 0.98,
      motivationKeywords: [
        'Pflegefachfrau',
        'Ausbildung',
        'Intensivpflege',
        'telc B1 Certified',
        'Anerkennung',
        'German Nursing',
      ],
      videoDurationSeconds: 52,
      provenance: 'VERIFIED' as const,
      createdAt: new Date('2025-01-12T10:25:00Z'),
      updatedAt: new Date(),
    },
    recommendation: {
      id: 'rec-ananya-1',
      applicantId: 'applicant-ananya-nair',
      eligibilityStatus: 'ELIGIBLE' as const,
      completenessScore: 92,
      pathwaySummary:
        'Dual Vocational Training (Duale Ausbildung / Anpassungsqualifizierung) in Nursing. Guaranteed monthly training stipend of €1,250 - €1,450 / month.',
      missingRequirements: [
        {
          id: 'req-ananya-1',
          title: 'Defizitbescheid (State Nursing Recognition Notice)',
          category: 'Licensing',
          severity: 'CRITICAL',
          description:
            'Assessment by the state recognition authority (Bezirksregierung) detailing theoretical vs practical hours equivalence.',
          actionType: 'ANERKENNUNG_FILING',
          isCompleted: false,
        },
        {
          id: 'req-ananya-2',
          title: 'Pass Goethe/telc B2 Pflege Exam',
          category: 'Language Qualification',
          severity: 'CRITICAL',
          description:
            'German healthcare authorities require B2 level for direct patient care authorization.',
          actionType: 'GERMAN_B2_NURSING',
          isCompleted: false,
        },
      ],
      anabinInstitutionalStatus: 'H+ (Recognized Medical Vocational Body)',
      apsRequired: false,
      educaroServiceRouting: [
        {
          packageId: 'EDU-NURSING-CARE',
          serviceName: 'Educaro Care Nursing Guaranteed Employer Placement & Relocation',
          tier: 'Full Placement Guarantee',
          highlight: 'Zero upfront tuition, paid German hospital contract & accommodation assist',
          matchScore: 99,
          features: [
            'Direct interview with vetted hospital groups in NRW & Hesse',
            'Official Defizitbescheid and Anerkennung filing through Educaro legal team',
            'Intensive Medical German B2 (B2 Pflege) coaching',
            'Visa processing under §16d or §18a AufenthG without blocked account requirement',
            'Airport pickup, apartment onboarding, and local Educaro mentor in Germany',
          ],
        },
      ],
      actionableNextSteps: [
        { step: 1, text: 'Translate and notarize GNM syllabus and clinical logbook' },
        { step: 2, text: 'Attend virtual employer interview with German hospital clinic' },
        { step: 3, text: 'Complete B2 Pflege module while awaiting Defizitbescheid' },
        { step: 4, text: 'Apply for German Work/Training Visa with signed employment contract' },
      ],
      aiSummaryNotes:
        'Outstanding candidate for Educaro Nursing track. Ananya already possesses telc B1 and 18 months ICU experience. German hospitals actively sponsor visa and relocation for this profile with monthly stipend.',
      generatedAt: new Date('2025-01-12T10:30:00Z'),
      updatedAt: new Date(),
    },
  },
  {
    id: 'applicant-vikram-patel',
    fullName: 'Vikram Patel',
    email: 'vikram.patel@example.com',
    phone: '+91 99887 65432',
    city: 'Bengaluru',
    state: 'Karnataka',
    country: 'India',
    targetIntake: 'Immediate 2025',
    availabilityDate: new Date('2025-06-01'),
    goalTrack: 'Employment' as const,
    status: 'ROADMAP_READY' as const,
    provenance: 'APPLICANT_PROVIDED' as const,
    createdAt: new Date('2025-01-15T11:00:00Z'),
    updatedAt: new Date(),
    educations: [
      {
        id: 'edu-vikram-1',
        applicantId: 'applicant-vikram-patel',
        institution: 'Anna University Chennai',
        qualification: 'Bachelor of Technology (B.Tech) Mechanical & Automation',
        fieldOfStudy: 'Mechanical & Automotive Systems',
        startYear: 2017,
        graduationYear: 2021,
        gpaOrPercentage: 7.9,
        maxGpaOrScale: 10.0,
        germanGpaEquivalent: 2.1,
        gradingSystem: 'CGPA_10',
        isIndianDegree: true,
        degreeType: 'FOUR_YEAR_BACHELOR' as const,
        anabinStatus: 'H+',
        isVerified: true,
        provenance: 'VERIFIED' as const,
        createdAt: new Date('2025-01-15T11:05:00Z'),
        updatedAt: new Date(),
      },
    ],
    employments: [
      {
        id: 'emp-vikram-1',
        applicantId: 'applicant-vikram-patel',
        employer: 'Tata Motors Passenger Vehicles',
        role: 'Senior CAE Automotive Simulation Engineer',
        responsibilities:
          'Structural FEA simulation using ANSYS and HyperWorks, crash safety analysis for EV vehicle platforms.',
        startDate: new Date('2021-08-01'),
        endDate: null,
        isCurrent: true,
        totalMonths: 42,
        industry: 'Mechanical / Automotive',
        isVerified: true,
        provenance: 'VERIFIED' as const,
        createdAt: new Date('2025-01-15T11:10:00Z'),
        updatedAt: new Date(),
      },
    ],
    languages: [
      {
        id: 'lang-vikram-1',
        applicantId: 'applicant-vikram-patel',
        language: 'German',
        level: 'A1',
        certificateName: 'Goethe-Zertifikat A1',
        score: '75/100',
        isVerified: true,
        provenance: 'VERIFIED' as const,
        createdAt: new Date('2025-01-15T11:15:00Z'),
        updatedAt: new Date(),
      },
      {
        id: 'lang-vikram-2',
        applicantId: 'applicant-vikram-patel',
        language: 'English',
        level: 'C1',
        certificateName: 'TOEFL iBT',
        score: '102/120',
        isVerified: true,
        provenance: 'APPLICANT_PROVIDED' as const,
        createdAt: new Date('2025-01-15T11:18:00Z'),
        updatedAt: new Date(),
      },
    ],
    documents: [
      {
        id: 'doc-vikram-1',
        applicantId: 'applicant-vikram-patel',
        title: 'Anna University B.Tech Degree Certificate & Experience Letter',
        docType: 'DEGREE_CERTIFICATE' as const,
        fileUrl: '/uploads/samples/vikram_anna_univ.pdf',
        fileName: 'vikram_anna_univ.pdf',
        fileSizeBytes: 2150000,
        mimeType: 'application/pdf',
        extractionFlags: {
          parsed: true,
          ocrConfidence: 0.97,
        },
        extractedData: {
          degree: 'B.Tech Mechanical Engineering',
          experienceMonths: 42,
          currentCompany: 'Tata Motors',
        },
        verificationState: 'VERIFIED' as const,
        verificationNotes: 'Verified against Anabin H+ institution standard.',
        uploadedAt: new Date('2025-01-15T11:20:00Z'),
        updatedAt: new Date(),
      },
    ],
    motivationMedia: {
      id: 'mot-vikram-1',
      applicantId: 'applicant-vikram-patel',
      primaryReasonToMigrate:
        'To work in Germany’s world-leading automotive & e-mobility sector (Stuttgart, Wolfsburg, Munich) under the new German Opportunity Card (Chancenkarte) or EU Blue Card.',
      targetRegionsInGermany: [
        'Baden-Württemberg (Stuttgart)',
        'Bavaria (Ingolstadt / Munich)',
        'Lower Saxony (Wolfsburg)',
      ],
      longTermCareerGoals:
        'Join Porsche, Audi, or Bosch as a Senior Automotive Simulation Specialist focusing on Next-Gen Electric Powertrains.',
      preferredLanguageOfStudyWork: 'English',
      introVideoUrl: '/uploads/videos/vikram_automotive.mp4',
      introVideoTranscript:
        'Hi, I am Vikram Patel from Bengaluru. I have 3.5 years of experience at Tata Motors specializing in finite element analysis and crash simulation for EV chassis. Germany is the automotive engineering capital of the world. With my recognized 4-year engineering degree and experience, I qualify for 8 points on the Chancenkarte points grid. I am seeking guidance from Educaro to fast-track my German job search and visa filing.',
      audioTranscript:
        'Hi, I am Vikram Patel from Bengaluru. I have 3.5 years of experience at Tata Motors...',
      sentimentScore: 0.91,
      motivationKeywords: [
        'Chancenkarte',
        'Automotive CAE',
        'FEA Simulation',
        'EU Blue Card',
        'Tata Motors',
        'Engineering Jobs',
      ],
      videoDurationSeconds: 45,
      provenance: 'APPLICANT_PROVIDED' as const,
      createdAt: new Date('2025-01-15T11:25:00Z'),
      updatedAt: new Date(),
    },
    recommendation: {
      id: 'rec-vikram-1',
      applicantId: 'applicant-vikram-patel',
      eligibilityStatus: 'ELIGIBLE' as const,
      completenessScore: 85,
      pathwaySummary:
        'Opportunity Card (Chancenkarte - Points-Based Jobseeker Visa) & EU Blue Card (Blaue Karte EU). Achieves 8 points (minimum 6 required).',
      missingRequirements: [
        {
          id: 'req-vikram-1',
          title: 'ZAB Statement of Comparability / Anabin Printout',
          category: 'Degree Recognition',
          severity: 'CRITICAL',
          description:
            'Official recognition proof from Central Office for Foreign Education (ZAB) confirming degree equivalency to a German Diplom-Ingenieur / Bachelor.',
          actionType: 'ZAB_FILING',
          isCompleted: false,
        },
        {
          id: 'req-vikram-2',
          title: 'Upgrade German to A2/B1',
          category: 'Language Qualification',
          severity: 'RECOMMENDED',
          description:
            'While engineering simulations are English-friendly, German A2/B1 grants +1 point on Chancenkarte and expands employer interviews.',
          actionType: 'GERMAN_A2',
          isCompleted: false,
        },
      ],
      anabinInstitutionalStatus: 'H+ (Full Institutional Equivalence)',
      apsRequired: false,
      educaroServiceRouting: [
        {
          packageId: 'EDU-OPPORTUNITY-CARD',
          serviceName: 'Educaro Opportunity Card (Chancenkarte) & German Career Matching',
          tier: 'Skilled Professional',
          highlight: 'Points calculation verification, direct German CV optimization & interview coaching',
          matchScore: 95,
          features: [
            'Chancenkarte points dossier preparation for German consulate submission',
            'German DIN 5008 Lebenslauf (CV) engineering rewrite',
            'Direct introduction to German automotive engineering staffing partners',
            'German labor market registration and job search visa assistance',
          ],
        },
      ],
      actionableNextSteps: [
        { step: 1, text: 'Obtain certified Anabin H+ institution and degree match printout' },
        { step: 2, text: 'Translate experience certificates and format German Lebenslauf' },
        { step: 3, text: 'Book Opportunity Card appointment at VFS / German Consulate Bengaluru' },
      ],
      aiSummaryNotes:
        'Vikram scores 8 points on the Chancenkarte (4 points for degree, 2 points for 3+ years experience, 1 point for age under 35, 1 point for C1 English). High chances of securing direct employment in Germany.',
      generatedAt: new Date('2025-01-15T11:30:00Z'),
      updatedAt: new Date(),
    },
  },
];
